spring.application.name=demo

# 設定 JSP 視圖解析路徑
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

# H2 Database 設定
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# MyBatis 設定
mybatis.configuration.map-underscore-to-camel-case=true
logging.level.com.example.demo.mapper=DEBUG

# 資料庫初始化設定
spring.sql.init.mode=always
